java {
    toolchain.languageVersion = JavaLanguageVersion.of(16)
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16
}

dependencies {
    implementation "org.slf4j:slf4j-api:2.0.9"
    implementation "com.google.code.gson:gson:2.8.0"
    implementation "org.jetbrains:annotations:24.1.0"
    my ("com.googlecode.soundlibs:mp3spi:1.9.5.4") {
        exclude group: 'com.googlecode.soundlibs', module: 'tritonus-share'
    }
    my 'com.github.GregTaoo:JustFLAC:85f0934435'
    my 'com.github.trilarion:vorbis-support:1.1.0'
    my ('com.googlecode.soundlibs:tritonus-all:0.3.7.2') {
        exclude group: 'com.googlecode.soundlibs', module: 'tritonus-share'
    }

    my 'com.google.zxing:core:3.5.4'
    my 'net.jthink:jaudiotagger:3.0.1'
}

jar {
    manifest {
        attributes([
                // 默认模块名 core 和 zxing 库的 core 重名, 会导致 zxing 库无法加载, 因此改为 top.gregtao.concerto.core
                'Automatic-Module-Name': 'top.gregtao.concerto.core'
        ])
    }
}