name: Build All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          cache: gradle
          java-version: |
            16
            17
            21

      - name: Build All Modules
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Forge Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: forge-artifacts
          path: |
            forge/forge-*/build/libs/*-all.jar

      - name: Upload NeoForge Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neoforge-artifacts
          path: |
            neoforge/neoforge-*/build/libs/*-all.jar